export const CHANGE_SONG_DETAIL="player/CHANGE_SONG_DETAIL";

export const CHANGE_PLAY_LIST="player/CHANGE_PLAY_LIST";
export const CHANGE_CURRENT_SONG_INDEX="player/CHANGE_CURRENT_SONG_INDEX";

export const CHANGE_SEQUENCE="player/CHANGE_SEQUENCE"

export const CHANGE_LOCK="player/CHANGE_LOCK"


export const CHANGE_SHOW_LPAYLIST="player/CHANGE_SHOW_LPAYLIST"

export const CHANGE_SONG_LYRIC_LIST="player/CHANGE_SONG_LYRIC_LIST"